spring:
  profiles.active: local

  datasource:
    url: "jdbc:mysql://localhost:3306/blog?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false"

logging:
  config: "src/main/resources/config/log4j2.yml"



---

spring:
  profiles: local
  datasource:
      username: root
      password: liuhanyu
      driver-class-name: com.mysql.jdbc.Driver

---

spring:
  profiles: test
  datasource:
      username: root
      password: wrong
      driver-class-name: com.mysql.jdbc.Driver

---

spring:
  profiles: stage
  datasource:
      username: root
      password: liuhanyu
      driver-class-name: com.mysql.jdbc.Driver

---

spring:
  profiles: prod
  datasource:
    username: root
    password: liuhanyu
    driver-class-name: com.mysql.jdbc.Driver
